### ISSUE TITLE
declaring any new real or inline function results in TypeError: Cannot read properties of null (reading 'content')

### ISSUE THREAD

**Issue by KonradHoeffner** [KonradHoeffner/top-frontend#1]
In `./src/components/Query/GridDialog.vue` inside `<script setup>`, adding any new function with a parameter causes the following build error:

```
0.755  App • Running "@quasar/testing" Quasar App Extension...
0.758  App • Running "@quasar/testing-unit-jest" Quasar App Extension...
1.094  App • Chaining "UI" Webpack config
1.190  App • Cleaned build artifact: "/app/dist/spa"
1.462  App •  WAIT  • Compiling of "UI" in progress...
18.13  App •  DONE  • "UI" compiled with errors • 16670ms
18.13 
18.13  App •  ERROR  •  UI  in ./src/components/Query/GridDialog.vue?vue&type=script&setup=true&lang=js
18.13 
18.13 Syntax Error: TypeError: Cannot read properties of null (reading 'content')
18.13     at selectBlock (/app/node_modules/vue-loader/dist/select.js:23:45)
18.13     at Object.loader (/app/node_modules/vue-loader/dist/index.js:92:41)
18.13 
18.13 
18.13  App •  COMPILATION FAILED  • Please check the log above for details.
```

**Comment by KonradHoeffner** [comment]
Closing this as it occurred during work on the data table, which is finished.
